[global]
server_name = "localhost"
database_backend = "rocksdb"
database_path = "/var/lib/matrix-conduit/"
address = "0.0.0.0"
port = 6167
max_request_size = 20000000
allow_registration = true
allow_federation = false
allow_check_for_updates = false
trusted_servers = ["matrix.org"]
